### ISSUE TITLE
Feature Request: Set the output path of the report file (+ silent mode)

### ISSUE THREAD

**Issue by Darkem1** [JPCERTCC/EmoCheck#1]
It would be nice to specify the output path of the report with a command line parameter. Also a silent mode would be great, so that the script can be executed on many systems at the same time in the background.

**Comment by Saxomania** [comment]
and may configure two different output filenames, one for not infected and another for infected

**Comment by BadgerRox** [comment]
As temporary Workaround:
I wrote a Powershell-Script to run EmoCheck as scheduled task and output the logs to the Windows Event Logs. 
I published the code at a [German IT Board](https://administrator.de/wissen/emocheck-start-powershell-eventlog-543927.html).
Attention: it's just alpha :)

**Comment by t-tani** [comment]
Thank you for the feedback!
I'll implement these requests in the next release.

**Comment by Lecatron** [comment]
Hey, i think it would also be nice to have the hostname of the scanned system in the name of the log. so you can automatically scan as many systems as possible and check the reports afterwards.

Íf i have time for this, i will add this feature today.

**Comment by t-tani** [comment]
I changed the log filename to use hostname(computer name) and timestamp in the next release.
Please wait for the next release.

**Comment by t-tani** [comment]
The following options will also be included in the next release.
- silent mode (no console output)
- changing the output path of the report

**Comment by Lecatron** [comment]
Hey t-tani, 

I just have done the silent mode, if you want, i can send you my code.

**Comment by t-tani** [comment]
All requests in here is supported in v0.0.2.
Thanks.
