### ISSUE TITLE
Further keywords that Emotet uses

### ISSUE THREAD

**Issue by ZiMADE** [JPCERTCC/EmoCheck#6]
First of all: many thanks for your great work and the possibility to get the code. 
I'm the author of [EmoKill](https://github.com/ZiMADE/EmoKill/) which will not only detect processes of Emotet, it also kills those processes as soon as possible. 

I've found references to further keywords that Emotet uses, it's documented at the following website of [F-Secure](https://www.f-secure.com/v-descs/trojan_w32_emotet.shtml). What do you think about integration of these keywords to EmoCheck?

**Comment by t-tani** [comment]
The keyword list written on the F-Secure website is an old Emotet that is not used in recent days. Emotet has a function to replace itself with a new binary if it's connected to the C2. Therefore the keyword list you pointed only detects old Emotet, which is not connected to the C2. 

EmoCheck is targeting the active Emotet dropper. Thus we have no plan to integrate old keyword lists.
